"""Trusted Lean checking and proof-term dependency inspection."""

from proof_faithfulness.lean.artifacts import (
    LeanArtifactError,
    check_and_persist_candidate,
    load_check_outcome,
    load_check_result,
    persist_check_outcome,
)
from proof_faithfulness.lean.checker import (
    FAILURE_AXIOM_AUDIT,
    FAILURE_EXTRACTION,
    FAILURE_MULTIPLE_BLOCKS,
    FAILURE_PROHIBITED_AXIOM,
    FAILURE_PROHIBITED_SORRY,
    FAILURE_SANDBOX,
    FAILURE_STATEMENT_CHANGED,
    FAILURE_SUCCESS,
    FAILURE_SYNTAX,
    FAILURE_TIMEOUT,
    FAILURE_TRUST_BYPASS,
    FAILURE_TYPE,
    CheckOutcome,
    LeanCandidateSpec,
    check_candidate,
    hash_lean_statement,
    network_isolation_probe,
)
from proof_faithfulness.lean.dependency import (
    BindingUse,
    DependencyProbeError,
    DependencyReport,
    LocalFactUse,
    probe_dependencies,
)

__all__ = [
    "FAILURE_AXIOM_AUDIT",
    "FAILURE_EXTRACTION",
    "FAILURE_MULTIPLE_BLOCKS",
    "FAILURE_PROHIBITED_AXIOM",
    "FAILURE_PROHIBITED_SORRY",
    "FAILURE_SANDBOX",
    "FAILURE_STATEMENT_CHANGED",
    "FAILURE_SUCCESS",
    "FAILURE_SYNTAX",
    "FAILURE_TIMEOUT",
    "FAILURE_TRUST_BYPASS",
    "FAILURE_TYPE",
    "BindingUse",
    "CheckOutcome",
    "DependencyProbeError",
    "DependencyReport",
    "LeanArtifactError",
    "LeanCandidateSpec",
    "LocalFactUse",
    "check_and_persist_candidate",
    "check_candidate",
    "hash_lean_statement",
    "load_check_outcome",
    "load_check_result",
    "network_isolation_probe",
    "persist_check_outcome",
    "probe_dependencies",
]
